import axiosInstance from '@/services/axiosInstance';
import { AUTH_ENDPOINTS } from '@/constants/apiEndpoints';
import type { ApiResponse } from '@/types/api.types';
import type {
  LoginPayload,
  RegisterPayload,
  LoginResponseData,
  RegisterResponseData,
  User,
  ChangePasswordPayload,
  ForgotPasswordPayload,
  ResetPasswordPayload,
} from '@/types/auth.types';

/**
 * authService
 *
 * Centralized service module for handling authentication-related API communications.
 * All methods leverage the `axiosInstance` interceptor, ensuring consistent
 * header management (e.g., JWT injection) and global error handling.
 *
 * Note: These methods return the resolved `data` property of the `ApiResponse`
 * directly, abstracting the Axios response wrapper for cleaner consumption in
 * application logic (Hooks/Components).
 */
export const authService = {
  // ==========================================
  // Core Authentication Flow
  // ==========================================

  /**
   * Authenticates a user and establishes a session.
   * @param payload - Contains user credentials (e.g., email/username and password).
   * @returns The user data and access token payload upon successful authentication.
   */
  login: (payload: LoginPayload) =>
    axiosInstance
      .post<ApiResponse<LoginResponseData>>(AUTH_ENDPOINTS.LOGIN, payload)
      .then((res) => res.data),

  /**
   * Registers a new user account.
   * @param payload - Registration details including required fields (e.g., email, password).
   * @returns Data associated with the newly created account.
   */
  register: (payload: RegisterPayload) =>
    axiosInstance
      .post<ApiResponse<RegisterResponseData>>(AUTH_ENDPOINTS.REGISTER, payload)
      .then((res) => res.data),

  /**
   * Terminates the current session on the server side.
   * Usually triggers the removal of cookies or invalidation of tokens.
   */
  logout: () =>
    axiosInstance
      .post<ApiResponse<null>>(AUTH_ENDPOINTS.LOGOUT, {})
      .then((res) => res.data),

  /**
   * Refreshes the authentication state.
   * This is typically invoked automatically by the Axios Interceptor when an
   * `access_token` expires. It uses the `refresh_token` stored in HTTP-only cookies.
   */
  refreshToken: () =>
    axiosInstance
      .post<ApiResponse<{ accessToken: string }>>(
        AUTH_ENDPOINTS.REFRESH_TOKEN,
        {}
      )
      .then((res) => res.data),

  // ==========================================
  // User Context & Validation
  // ==========================================

  /**
   * Fetches profile information for the currently authenticated user.
   * Requires a valid access token in the request headers.
   */
  getMe: () =>
    axiosInstance
      .get<ApiResponse<User>>(AUTH_ENDPOINTS.ME)
      .then((res) => res.data),

  /**
   * Verifies the user's email address using a token received via email.
   * @param token - The verification string generated by the backend.
   */
  verifyEmail: (token: string) =>
    axiosInstance
      .get<ApiResponse<null>>(AUTH_ENDPOINTS.VERIFY_EMAIL(token))
      .then((res) => res.data),

  // ==========================================
  // Account Security & Password Management
  // ==========================================

  /**
   * Initiates the password recovery flow by sending a reset link to the user's email.
   * @param payload - Identifying information, typically the email address.
   */
  forgotPassword: (payload: ForgotPasswordPayload) =>
    axiosInstance
      .post<ApiResponse<null>>(AUTH_ENDPOINTS.FORGOT_PASSWORD, payload)
      .then((res) => res.data),

  /**
   * Completes the password reset process using the reset token.
   * @param payload - Contains the reset token and the new password.
   */
  resetPassword: (payload: ResetPasswordPayload) =>
    axiosInstance
      .post<ApiResponse<null>>(AUTH_ENDPOINTS.RESET_PASSWORD, payload)
      .then((res) => res.data),

  /**
   * Updates the user's password while currently authenticated.
   * @param payload - Current password (for verification) and the new password.
   */
  changePassword: (payload: ChangePasswordPayload) =>
    axiosInstance
      .patch<ApiResponse<null>>(AUTH_ENDPOINTS.CHANGE_PASSWORD, payload)
      .then((res) => res.data),
};
